version: 2
updates:
  # ===========================
  # NPM Updates (Weekly)
  # ===========================
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(npm): [skip ci]'
    labels:
      - 'dependencies'
      - 'npm'
    versioning-strategy: increase
    groups:
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: 'development'

  # ===========================
  # GitHub Actions Updates (Weekly)
  # ===========================
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(actions): [skip ci]'
    labels:
      - 'dependencies'
      - 'github-actions'
    groups:
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: 'development'
