name: 'Pull Request Labeler'

on:
  - pull_request_target

jobs:
  labeler:
    uses: SP-Libraries/actions/.github/workflows/pr-labeler.yml@v0.4.1
    with:
      VERBOSE: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions:
      issues: write
      contents: read
      pull-requests: write
