name: "Pull Request Labeler"

on:
  - pull_request_target

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  labeler:
    uses: SP-Packages/actions/.github/workflows/pr-labeler.yml@v1.1.2
    permissions:
      contents: read
      pull-requests: write
