name: 'Pull Request Labeler'

on:
  - pull_request_target

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  labeler:
    uses: SP-Packages/actions/.github/workflows/pr-labeler.yml@v1.1.9
